In [ ]:
import pandas as pd

In [ ]:
data={"name":["A","B","C"],"age":[20,18,22],"marks":[75,82,68]}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
print(df)

  name  age  marks
0    A   20     75
1    B   18     82
2    C   22     68

In [ ]:
df["marks"]

0    75
1    82
2    68
Name: marks, dtype: int64

In [ ]:
df["marks"]+5

0    80
1    87
2    73
Name: marks, dtype: int64

In [ ]:
s=pd.Series([10,20,30,40], index=['a','b','c','d'])

In [ ]:
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
df.head()

  name  age  marks
0    A   20     75
1    B   18     82
2    C   22     68

In [ ]:
df.shape

(3, 3)

In [ ]:
df = pd.read_csv("/Data - Sheet1.csv")

In [ ]:
df.head()

   SNo Roll Number Name Branch  Hobby-1    Hobby-2    Place  Marks  Age
0    1         5v5   h1    cse   vibing   swimming      hyd     98   18
1    2         5v6   h2    ece  classes  listening    vizag     90   23
2    3         5v7   h3     am    dance      music      blr     67   19
3    4         5v8   h4     gk    sleep     movies  chennai     54   20
4    5         5v9   h5   itws   vibing   swimming      hyd     45   21

In [ ]:
df.info

<bound method DataFrame.info of     SNo Roll Number Name Branch  Hobby-1    Hobby-2    Place  Marks  Age
0     1         5v5   h1    cse   vibing   swimming      hyd     98   18
1     2         5v6   h2    ece  classes  listening    vizag     90   23
2     3         5v7   h3     am    dance      music      blr     67   19
3     4         5v8   h4     gk    sleep     movies  chennai     54   20
4     5         5v9   h5   itws   vibing   swimming      hyd     45   21
5     6        5v10   h6    eee  classes  listening    vizag     56   22
6     7        5v11   h7    dms    dance      music      blr     78   23
7     8        5v12   h8   dbms    sleep     movies  chennai     89   24
8     9        5v13   h9    aep   vibing   swimming      hyd     45   25
9    10        5v14  h10    bee  classes  listening    vizag     20   26
10   11        5v15  h11    cse    dance      music      blr     45   27
11   12        5v16  h12    ece    sleep     movies  chennai     98   28
12   13        5v17  h13     am   vibing   swimming      hyd     37   29
13   14        5v18  h14     gk  classes  listening    vizag     56   30
14   15        5v19  h15   itws    dance      music      blr     53   31
15   16        5v20  h16    eee    sleep     movies  chennai     34   32
16   17        5v21  h17    dms   vibing   swimming      hyd     65   33
17   18        5v22  h18   dbms  classes  listening    vizag     34   34
18   19        5v23  h19    aep    dance      music      blr     23   35
19   20        5v24  h20    bee    sleep     movies  chennai     98   36>

In [ ]:
df["Marks"].median()

55.0

In [ ]:
df["Marks"].mode()

0    45
1    98
Name: Marks, dtype: int64

In [ ]:
df["Marks"].max()
df["Marks"].quantile(0.25)
df["Marks"].quantile(0.50)
df["Marks"].quantile(0.75)

np.float64(80.75)

In [ ]:
df["Marks"].std()

25.23755555766675

In [ ]:
df["Marks"].min()

20

In [ ]:
df["Marks"].mean()

np.float64(59.25)